package StepDef;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import io.qameta.allure.*;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import static java.lang.Thread.sleep;

public class ExampleSteps {


    private static String schedule_css = " #app > div > div > div.Banner-sc-1p31lg7-0.iBPHCr div";
    private static String Firstname_css = "div label:nth-child(4) div input";
    private static String LastName_css = " div label:nth-child(5) div input";
    private static String Email_css = " div label:nth-child(6) div input";
    private static String phone_css = " div label:nth-child(7) div input";

    WebDriver driver;
    @Given("I have a cucumber feature file")
    @AllureId("1")
    @Description("verify url should open successfully")
    @Severity(SeverityLevel.BLOCKER)
    @Test
    public void iHaveACucumberFeatureFile()
    {
        System.setProperty("webdriver.chrome.driver", "C:\\Users\\Documents\\chromedriver.exe");
        driver = new ChromeDriver();
        driver.get("http://18.188.38.38/login");


// Step definition code goes here
    }

    @When("I run the feature file with cucumber")
    @AllureId("2")
    @Description("verify input fields")
    @Test
    public void iRunTheFeatureFileWithCucumber() {
        //sleep(9000);
        driver.findElement(By.cssSelector("#app > div > div > div.Banner-sc-1p31lg7-0.iBPHCr div")).click();
        driver.findElement(By.cssSelector(Firstname_css)).sendKeys("Fizza");
        driver.findElement(By.cssSelector(LastName_css)).sendKeys("Jawed");
        driver.findElement(By.cssSelector(Email_css)).sendKeys("fizzashaikh34@gmail.com");
    }





// Step definition code goes here


    @Then("I should see a report generated by allure")
    public void iShouldSeeAReportGeneratedByAllure() {
// Step definition code goes here
    }
}
